

services:
  backend:
    build: ./backend
    container_name: backendContainer    
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    container_name: frontendContainer
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend